baseURL = 'https://trungkien2543.github.io/fcj-workshopz/'
languageCode = 'en-us'
title = ''

theme = 'hugo-theme-relearn'

# Thêm dòng này để đảm bảo các link tương đối
relativeURLs = true

[params]

  custom_css = ["css/custom.css"]

  # Logo cho header
  [params.logo]
    path = "/images/logo.png"
    alt = "Logo"
    width = "40px"
    height = "40px"
  
  # Hoặc cách đơn giản hơn
  logoUrl = "/images/logo.png"

    
[languages]
  [languages.vi]
    languageName = 'Tiếng Việt'
    weight = 1
    [languages.vi.params]
      landingPageName = "Trang chủ"
    
  [languages.en]
    languageName = 'English'
    weight = 2
    [languages.en.params]
      landingPageName = "Home"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
