# Base URL GitHub Pages
baseURL = "https://trungkien2543.github.io/fcj-workshopz/"
languageCode = "en-us"
title = "My Hugo Site"
theme = "hugo-theme-relearn"

# Relative URLs giúp link CSS/JS/ảnh đúng cả khi deploy subpath
# relativeURLs = true
canonifyURLs = true

[minify]
  disableXML = true


[params]

  # Custom CSS
  custom_css = ["css/custom.css"]

  # Logo header
  [params.logo]
    path = "images/logo.png"   # không có '/' đầu tiên
    alt = "Logo"
    width = "40px"
    height = "40px"

  logoUrl = "images/logo.png"

[languages]

  [languages.vi]
    languageName = "Tiếng Việt"
    weight = 1
    [languages.vi.params]
      landingPageName = "Trang chủ"

  [languages.en]
    languageName = "English"
    weight = 2
    [languages.en.params]
      landingPageName = "Home"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
